### ISSUE TITLE
Needs to add website link

### ISSUE THREAD

**Issue by Jobin-S** [TSharvananthan/NeonUpgrade#1]
Needs to add website link in readme.md

- [ ] to add link in readme

**Comment by TSharvananthan** [comment]
currently working to get a working link

**Comment by Jobin-S** [comment]
set the main branch in setting to get
the owner will get access to setting

**Comment by TSharvananthan** [comment]
Thanks for the help brother
https://tsharvananthan.github.io/NeonUpgrade/
Heres the link. Future plans to add a CNAME :)

**Comment by TSharvananthan** [comment]
Thanks for the help brother
https://tsharvananthan.github.io/NeonUpgrade/
Heres the link. Future plans to add a CNAME :)
